version: "3"

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbit-nerdstore
    environment:
      RABBITMQ_DEFAULT_USER: "nerdstore"
      RABBITMQ_DEFAULT_PASS: "nerdstore"

  sql-server:
    image: vitorinoue/nerdstore-sql-server:latest
    container_name: nerdstore-sql-server
    build:
      context: ../sql
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  web-mvc:
    image: vitorinoue/nerdstore-web-mvc-ecommerce:latest
    #container_name: nerdstore-web-mvc-ecommerce
    build:
      context: ../src
      dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5001
    volumes:
      - dpkeys:/var/data_protection_keys/
    depends_on:
      - api-catalogo
      - api-identidade
      - api-cliente
      - api-bff-compras

  api-identidade:
    image: vitorinoue/nerdstore-api-identidade:latest
    container_name: nerdstore-api-identidade
    build:
      context: ../src
      dockerfile: ./services/NSE.Identidade.API/Dockerfile
    restart: always
    ports:
      - "5101:5101"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5101;http://+5102
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server

  api-carrinho:
    image: vitorinoue/nerdstore-api-carrinho:latest
    container_name: nerdstore-api-carrinho
    build:
      context: ../src
      dockerfile: ./services/NSE.Carrinho.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5201;http://+5202
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server

  api-catalogo:
    image: vitorinoue/nerdstore-api-catalogo:latest
    container_name: nerdstore-api-catalogo
    build:
      context: ../src
      dockerfile: ./services/NSE.Catalogo.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5301;http://+5302
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server

  api-cliente:
    image: vitorinoue/nerdstore-api-cliente:latest
    container_name: nerdstore-api-cliente
    build:
      context: ../src
      dockerfile: ./services/NSE.Clientes.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5401;http://+5402
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - sql-server

  api-bff-compras:
    image: vitorinoue/nerdstore-api-bff-compras:latest
    container_name: nerdstore-api-bff-compras
    build:
      context: ../src
      dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5501;http://+5502
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - api-carrinho
      - api-pagamento
      - api-pedido

  api-pagamento:
    image: vitorinoue/nerdstore-api-pagamento:latest
    container_name: nerdstore-api-pagamento
    build:
      context: ../src
      dockerfile: ./services/NSE.Pagamentos.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5601;http://+5602
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - api-identidade
      - api-pedido
      - sql-server

  api-pedido:
    image: vitorinoue/nerdstore-api-pedido:latest
    container_name: nerdstore-api-pedido
    build:
      context: ../src
      dockerfile: ./services/NSE.Pedidos.API/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5701;http://+5702
      - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
    volumes:
      - ./certs:/https:ro
    depends_on:
      - rabbitmq
      - sql-server
      - api-identidade

  nerdstore-server:
    image: vitorinoue/nerdstore-server:latest
    container_name: nerdstore-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-mvc

volumes:
  dpkeys:
